### ISSUE TITLE
Caught an error with Next.js

### ISSUE THREAD

**Issue by lightsound** [zx6658/css-in-js-media#10]
I want to use `css-in-js-media` with Next.js, but error is occurred.

I wrote the same code as the README. 

Could you let me know the cause? 🙏

The following is screenshot.
![スクリーンショット 2020-03-17 14 09 20](https://user-images.githubusercontent.com/8220973/76824014-2af07080-6859-11ea-965c-f0c1342fad8d.png)

**Comment by zx6658** [comment]
Yes, I will check for you. can you tell me your next.js app version? @lightsound

**Comment by lightsound** [comment]
@zx6658 Thanks. I use v9.3.0.

**Comment by zx6658** [comment]
@lightsound Thanks for quick response :) I will fix for you soon 🙏

**Comment by zx6658** [comment]
@lightsound can you check with version css-in-js-media 1.0.9..? I updated it

**Comment by lightsound** [comment]
@zx6658 Thanks, but the bug was not fixed.

I also investigated the cause and found that SSR was related.
In the same Next.js project, there was no bug when it was not SSR.
But I don't know how to fix it.
I'd be glad if it was helpful information.

**Comment by zx6658** [comment]
@lightsound Can you check with version **1.0.11** again..? and I recommend you remove package-lock.json and test again..! :) I tested on my next.js app

**Comment by zx6658** [comment]
can you show me your code and error..?

**Comment by lightsound** [comment]
@zx6658 Woo! It worked. Thanks a lot. 🙏

You may not need it anymore, my code is the following.
![image](https://user-images.githubusercontent.com/8220973/76864919-42ede180-68a5-11ea-8990-25877cb35958.png)

**Comment by zx6658** [comment]
@lightsound I'm happy to hear that :). If you want to add or update new feature, It's free to contribute my library:) thanks ..!
